---

- name: Create /etc/traefik/htpasswd
  with_items: ['', '/htpasswd']
  file:
    path: /etc/traefik{{ item }}
    state: directory
    owner: root
    mode: 0755

- include_role: name=yourlabs.remember

- name: Ensure docker was setup once on this host
  include_role: name=thommignot.docker
  when: ansible_facts['ansible_local']['yourlabs_docker']['state']|default('') != 'success'

- name: Install passlib library for ansible htpasswd module
  pip:
    name: passlib
    state: present

- name: Fetch password_root if any
  when: password != 'none'
  fetch:
    src: /root/password_root
    dest: password_root
    flat: true
  failed_when: false

- name: Create /etc/traefik/htpasswd
  file:
    path: /etc/traefik/htpasswd
    state: directory
    owner: root
    mode: 0755
    recurse: yes

- name: Upload traefik.toml
  template:
    src: '{{ role_path }}/traefik.toml'
    dest: '{{ home }}/traefik.toml'

- name: Generate htpasswd file
  when: password != 'none'
  htpasswd:
    password: "{{ password if password else lookup('password', 'password_root chars=ascii_letters length=32') }}"
    path: /etc/traefik/htpasswd/root
    name: root

- name: Upload {{ home }}/docker-compose.yml
  template:
    src: '{{ role_path }}/docker-compose.yml'
    dest: '{{ home }}/docker-compose.yml'

- name: Create web network
  docker_network:
    name: web

- name: Start {{ home }}/docker-compose.yml
  docker_compose:
    project_src: '{{ home }}'
    restarted: yes
    pull: yes
    recreate: always

- name: Upload password in /root/password_root
  when: password != 'none'
  copy:
    src: password_root
    dest: /root/password_root
    owner: root
    mode: 0600

- name: Remove local copy of password_root and htaccess
  changed_when: false
  file:
    path: '{{ item }}'
    state: absent
  with_items:
  - password_root
  - ./.tmp_traefik_htaccess

- include_tasks: check.yml
